apiVersion: btrix.cloud/v1
kind: BtrixJob
metadata:
  name: job-{{ id }}
  labels:
    crawl: "{{ id }}"
    role: "btrix-job"

spec:
  selector:
    matchLabels:
      crawl: "{{ id }}"

  manual: {{ manual }}
  id: "{{ id }}"
  jobId: "job-{{ id }}"
  userId: "{{ userid }}"
  orgId: "{{ oid }}"
  configId: "{{ cid }}"
  rev: "{{ rev }}"
  scale: "{{ scale }}"

  nodeType: "{{ crawler_node_type }}"
  jobImage: "{{ job_image }}"
  jobPullPolicy: "{{ job_pull_policy }}"
  tags: "{{ tags }}"

