---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: collindexes.btrix.cloud
spec:
  scope: Namespaced
  group: btrix.cloud
  names:
    kind: CollIndex
    plural: collindexes
    singular: collindex
    shortNames:
      - cixs

  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}

      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true

            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true

      additionalPrinterColumns:
        - name: State
          type: string
          jsonPath: .status.state
          description: Crawl State

        - name: Time Created
          type: date
          jsonPath: .metadata.creationTimestamp
          description: "time index created"

        - name: Time Updated
          type: date
          jsonPath: .status.updated
          description: "time index updated"
