---
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "npm"
    directory: "/emails"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "uv"
    directory: "/backend"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
...
