main_node_type: main
 
crawler_node_type: crawling
redis_node_type: crawling

backend_image: "registry.digitalocean.com/btrix/webrecorder/browsertrix-backend:latest"
frontend_image: "registry.digitalocean.com/btrix/webrecorder/browsertrix-frontend:latest"
crawler_image: "registry.digitalocean.com/btrix/webrecorder/browsertrix-crawler:latest"
crawler_pull_policy: "Always"

#rwp_base_url: "https://dev.replayweb.page/"

#crawler_args: "--logging pywb,stats,behaviors,debug --generateWACZ --text --collection thecrawl --screencastPort 9037 --waitOnDone"

# minimum size allocated to each crawler
# should be at least double crawl session size to ensure space for WACZ
crawler_requests_storage: "220Gi"

# max size at which crawler will commit current crawl session
crawler_session_size_limit_bytes: "100000000000"

# max time in seconds after which crawler will restart, if set
crawler_session_time_limit_seconds: 18000

# max pages
max_pages_per_crawl: 100000

# num workers
backend_workers: 4



mongo_local: true

mongo_auth:
  #db_url: "mongodb+srv://doadmin:96o57x1hW0j2Mr4s@private-btrix-dev-6ff0a7d1.mongo.ondigitalocean.com/admin?authSource=admin&tls=true"
  #db_url: "mongodb+srv://doadmin:21yW4BlOX0TI3795@private-btrix-stanford-0bfb9195.mongo.ondigitalocean.com/admin?tls=true&authSource=admin&replicaSet=btrix-stanford"
  username: rootadmin
  password: HighFidelity!

minio_local: false

crawler_requests_cpu: "1200m"
crawler_limits_cpu: "2500m"
crawler_requests_memory: "1200Mi"
crawler_limits_memory: "3200Mi"

storages:
  - name: "default"
    access_key: "GICUDSH5PVZLKEMMOYQV"
    secret_key: "FN+w/432l5gioObyPOwHbLuHfgdxtinK/z+7wr0CgUI"

    endpoint_url: "https://sfo2.digitaloceanspaces.com/btrix-dev/dev-2/"

superuser:
  email: dev@webrecorder.net
  password: HighFidelity!2


ingress:
  host: "dev.browsertrix.cloud"
  cert_email: "dev@webrecorder.net"
  scheme: "https"
  tls: true

extra_hosts:
  - dev-alt.browsertrix.cloud

signer:
  enabled: true
  host: "signing.dev.browsertrix.cloud"
  cert_email: "dev@webrecorder.net"
  image: webrecorder/authsign:0.5.0
  image_pull_policy: "IfNotPresent"
  auth_token: "07ac74c3-493e-46fe-bc3b-550895ac7bdd"

registration_enabled: "0"
jwt_token_lifetime_minutes: 3600

# Email Options
# =========================================
email:
  smtp_port: 587
  smtp_host: smtp.gmail.com
  sender_email: ilya@webrecorder.org
  password: gckciceosderepme


