[lint]
extend-select = [
	# Import sorting
	"I",
	# Error
	"PLE",
	# Warning
	"W",
	# flake8-builtins
	"A",
	# flake8-quotes
	"Q",
	# banned-api
	"TID251",
]
ignore = [
	# Comparison to true should be 'if cond is true:' or 'if cond:'
	"E712",
	# Do not use bare except, specify exception instead
	"E722",
	# Comparison to None should be 'cond is None:'
	"E711",
	# Module imported but unused
	"F401",
	# f string missing placeholders
	"F541",
	# unused variable
	"F841"
]
[lint.flake8-tidy-imports.banned-api]
"asyncio.create_subprocess_shell".msg = "Use the non-shell asyncio.create_subprocess_exec function instead."

[lint.isort]
force-to-top = ["logger"]
