---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: crawljobs.btrix.cloud
spec:
  scope: Namespaced
  group: btrix.cloud
  names:
    kind: CrawlJob
    plural: crawljobs
    singular: crawlob
    shortNames:
      - cjs
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
        scale:
          specReplicasPath: .spec.scale
          statusReplicasPath: .status.scale
          labelSelectorPath: .status.labelSelector

      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                id:
                  type: string
                userid:
                  type: string
                oid:
                  type: string
                cid:
                  type: string
                rev:
                  type: integer
                scale:
                  type: integer
                ttlSecondsAfterFinished:
                  type: integer
                forceRestart:
                  type: string
 
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                state:
                  type: string
                pagesDone:
                  type: integer
                pagesFound:
                  type: integer
                finished:
                  type: string
                filesAdded:
                  type: integer
                scale:
                  type: integer
                labelSelector:
                  type: string

      additionalPrinterColumns:
        - name: State
          type: string
          jsonPath: .status.state
          description: Crawl State

        - name: Pages Done
          type: integer
          jsonPath: .status.pagesDone
          description: Pages Done

        - name: Pages Found
          type: integer
          jsonPath: .status.pagesFound
          description: Pages Found

        - name: Time Started
          type: date
          jsonPath: .metadata.creationTimestamp
          description: "time crawl started"

        - name: Time Finished
          type: date
          jsonPath: .status.finished
          description: "if set, time crawl has finished"

        - name: Files Added
          type: integer
          jsonPath: .status.filesAdded
          description: "number of WACZ files uploaded so far from this crawl"

        - name: Scale
          type: integer
          jsonPath: .status.scale
          description: Crawl Scale

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: profilejobs.btrix.cloud
spec:
  scope: Namespaced
  group: btrix.cloud
  names:
    kind: ProfileJob
    plural: profilejobs
    singular: profilejob
    shortNames:
      - pjs

  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}

      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true

            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true

      additionalPrinterColumns:
        - name: Expire At
          type: string
          jsonPath: .spec.expireTime
          description: Time Browser will Expire

        - name: Start Url
          type: string
          jsonPath: .spec.startUrl
          description: Starting Url
