apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: btrixjobs.btrix.cloud
spec:
  scope: Namespaced
  group: btrix.cloud
  names:
    kind: BtrixJob
    plural: btrixjobs
    singular: btrixjob
    shortNames:
      - btrixjobs
      - btjobs
  versions:
    - name: v1
      served: true
      storage: true
      subresources: { status: { } }  # comment/uncomment for experiments
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Message
          type: string
          priority: 0
          jsonPath: .status.message
          description: As returned from the handler (sometimes).
        - name: Active
          type: integer
          priority: 0
          jsonPath: .status.active
          description: As returned from the handler (sometimes).
        - name: Ready
          type: integer
          priority: 0
          jsonPath: .status.ready
          description: As returned from the handler (sometimes).
        - name: Jobs
          type: integer
          priority: 0
          jsonPath: .status.jobs
          description: As returned from the handler (sometimes).
        - name: StartAt
          type: string
          priority: 0
          jsonPath: .status.startTime
          description: As returned from the handler (sometimes).
