{{- if .Values.redis_local }}

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-storage-pvc
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi

  {{- if .Values.volume_storage_class }}
  storageClassName: {{ .Values.volume_storage_class }}
  {{- end }}


{{- if not .Values.volume_storage_class }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "local-redis-store-pv"
  annotations:
    "helm.sh/resource-policy": keep
spec:
  capacity:
    storage: 1Gi

  accessModes:
    - "ReadWriteOnce"

  hostPath:
    path: /tmp/btrix-redis-data
{{- end }}


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-redis
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: local-redis

  replicas: 1
  template:
    metadata:
      labels:
        app: local-redis

    spec:
      volumes:
        - name: data-redis
          persistentVolumeClaim:
            claimName: redis-storage-pvc

      containers:
        - name: redis
          image: {{ .Values.redis_image }}
          imagePullPolicy: {{ .Values.redis_pull_policy }}

          args: ["--appendonly", "yes"]
          volumeMounts:
            - name: data-redis
              mountPath: /data
              subPath: redis

          resources:
            limits:
              cpu: {{ .Values.redis_limits_cpu }}
              memory: {{ .Values.redis_limits_memory }}

            requests:
              cpu: {{ .Values.redis_requests_cpu }}
              memory: {{ .Values.redis_requests_memory }}

          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping

---
apiVersion: v1
kind: Service

metadata:
  namespace: {{ .Release.Namespace }}
  name: local-redis
  labels:
    app: local-redis

spec:
  type: ClusterIP
  selector:
    app: local-redis

  ports:
    - protocol: TCP
      port: 6379
      name: redis

{{- end }}


