---
apiVersion: v1
kind: Service
metadata:
  name: crawler
  namespace: {{ .Values.crawler_namespace }}

spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    role: crawler

  ports:
    - protocol: TCP
      port: 9037
      name: screencast

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.crawler_namespace }}

spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    role: redis

  ports:
    - protocol: TCP
      port: 6379
      name: redis

---
apiVersion: v1
kind: Service
metadata:
  name: browser
  namespace: {{ .Values.crawler_namespace }}

spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    role: browser

  ports:
    - protocol: TCP
      port: 9223
      name: browser-api

    - protocol: TCP
      port: 9222
      name: browser-ws
