ingress:
  host: "myhostname"
  scheme: "https"
  tls: false

ingress_class: "nginx"
# for microk8s's ingress controller
# ingress_class: "public" 

addons:
  admin:
    logging: true

btrix-admin-logging:
  logging:
    enabled: true
    dedicatedNode:
      enabled: false
    ingress:
      tls: false
      class: "nginx"
      host: "myhostname"
    elasticsearch:
      local: true
    kibana:
      local: true
