# microk8s config overrides (local)
# ---------------------------------
#
# This config can be used to run with microk8s, locally w/o having to set the hostname.
# It is not designed for production use and does not use the ingress
#
# Enable microk8s add-ons with:
# microk8s enable dns hostpath-storage registry helm3
#
# 
# microk8s helm3 upgrade --install -f ./chart/values.yaml -f ./chart/examples/microk8s-local.yaml btrix ./chart/

# If developing locally, enable each image override to use image from local microk8s repo
# api_image: "localhost:32000/webrecorder/browsertrix-backend:latest"
# nginx_image: "localhost:32000/webrecorder/browsertrix-frontend:latest"
# crawler_image: "localhost:32000/webrecorder/browsertrix-crawler:latest"

# run service on localhost on port
nginx_service_localhost_port: 30870

# optionally, override default mongodb auth, used for all data storage:

#mongo_auth:
  #username: root
  #password: PASSWORD!
  

# optionally, set these to custom values

#superuser:
  # set this to enable a superuser admim
  # email: admin@example.com

  # optional: if not set, automatically generated
  # change or remove this
  # password: PASSWORD!

