apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ id }}"
  labels:
    role: "background-job"
    job_type: {{ job_type }}
    btrix.org: {{ oid }}

spec:
  ttlSecondsAfterFinished: 0
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      priorityClassName: bg-job
      podFailurePolicy:
        rules:
        - action: FailJob
          onExitCodes:
            containerName: btrixbgjob
            operator: NotIn
            values: [0]
      containers:
      - name: btrixbgjob
        image: {{ backend_image }}
        imagePullPolicy: {{ pull_policy }}
        env:
        - name: BG_JOB_TYPE
          value: {{ job_type }}

        - name: OID
          value: {{ oid }}

        command: ["python3", "/app/btrixcloud/main_bg.py"]

        resources:
          limits:
            memory: "200Mi"

          requests:
            memory: "200Mi"
            cpu: "50m"
