name: Bug Report
description: Report a demonstrable problem caused by code in this repo.
title: "[Bug]: "
labels: ["bug"]
type: "Bug"
body:
  # Version number
  - type: input
    id: version
    attributes:
      label: Browsertrix Version
      description: This can be found in the bottom end of the Browsertrix web app.
      placeholder: "v1.5.0-beta.0-67d0c6a"
    validations:
      required: true
  # What did the user expect to happen? What was the actual behavior?
  - type: textarea
    attributes:
      label: What did you expect to happen? What happened instead?
      description: |
        A clear and concise description of the bug, and what you expected to happen instead.
        
        For issues related to crawling or replay, please include a link to the archived item and workflow when possible.
    validations:
      required: true
  # Step-by-step reproduction instructions
  - type: textarea
    attributes:
      label: Reproduction instructions
      description: Step-by-step description of how to reproduce the issue, including the page URL if applicable.
      placeholder: |
        1. Navigate to...
        2. Click on...
        3. See error...
    validations:
      required: true
  # Screenshots / videos
  - type: textarea
    attributes:
      label: Screenshots / Video
      description: Please attach any screenshots or screen recordings that demonstrate the bug. You can attach images by clicking this area to highlight it and then dragging files into the browser window.
  # Environment
  - type: input
    attributes:
      label: Environment
      description: Please specify your browser if the issue is related to the web app, and provide information on your operating system if you're running Browsertrix locally.
      placeholder: |
        Browser:
        Browser version:
        OS:
  # Additional details
  - type: textarea
    attributes:
      label: Additional details
      description: Any additional context that helps us investigate the issue. For example, does the issue only happen in a specific browser? Are there forum discussions related to your issue? etc.
