name: Change Request
description: Request new functionality or changes to an existing feature.
title: "[Change]: "
labels: ["enhancement", "idea"]
type: "Feature"
body:
  # Deployment type
  - type: dropdown
    id: deployment
    attributes:
      label: Browsertrix Host
      description: Are you self-hosting Browsertrix, or are you on a hosted plan?
      options:
        - Self-Hosted
        - Hosted by Webrecorder
    validations:
      required: true
  - type: textarea
    attributes:
      label: What change would you like to see?
      description: |
        A clear and concise description of the change to existing functionality.

        For general ideas on how to improve Browsertrix, or if you have questions about 
        existing functionality, please check our [community forum](https://forum.webrecorder.net/) 
        before submitting a request.
      placeholder: I would like to be able to ____________ so that I can ____________.
    validations:
      required: true
  # Additional details
  - type: textarea
    attributes:
      label: Additional details
      description: Any additional context that helps us understand this request.