blank_issues_enabled: false

contact_links:
  - name: Ask a question
    url: https://forum.webrecorder.net/c/help/browsertrix/24
    about: Have a ("how do I...?") question? Not sure if your issue is reproducible? The best way to get help is on our community forum!
  - name: Report a replay issue
    about: Issues related to an archived item or collection not replaying properly should be reported in the ReplayWeb.page repo.
    url: https://github.com/webrecorder/replayweb.page/issues/new?&labels=replay+bug%2Cbug&projects=&template=replay-bug.yml&title=[Replay+Bug]%3A+
  - name: Report a security vulnerability
    about: Please email security@webrecorder.org directly. We will follow up with you there!
    url: https://webrecorder.net/.well-known/security.txt
  - name: Read the docs
    url: https://docs.browsertrix.com
    about: Find solutions to common questions, such as how to install, develop, and deploy Browsertrix.
