name: Feature / Change Request
description: Request a new feature or change to an existing feature of the app.
title: "[Feature]: "
labels: ["enhancement"]
body:
  # User story sentence
  - type: textarea
    attributes:
      label: What change would you like to see?
      description: Describe the improvement or feature you'd like added to Browsertrix.
      placeholder: I would like to be able to ____________ so that I can ____________.
    validations:
      required: true
  # Context
  - type: textarea
    attributes:
      label: Context
      description: Any background information that helps us understand the request.
    validations:
      required: true