import "./alert";
import "./badge";
import "./button";
import "./card";
import "./data-table";
import "./desc-list";
import "./dialog";
import "./link";
import "./navigation";
import "./tab-group";
import "./tab-list";
import "./url-input";

import("./code");
import("./combobox");
import("./config-details");
import("./copy-button");
import("./copy-field");
import("./details");
import("./file-list");
import("./format-date");
import("./inline-input");
import("./language-select");
import("./markdown-editor");
import("./markdown-viewer");
import("./menu-item-link");
import("./meter");
import("./numbered-list");
import("./overflow-dropdown");
import("./overflow-scroll");
import("./pagination");
import("./pw-strength-alert");
import("./relative-duration");
import("./search-combobox");
import("./section-heading");
import("./select-crawler-proxy");
import("./select-crawler");
import("./syntax-input");
import("./table");
import("./tag-input");
import("./tag");
import("./time-input");
import("./user-language-select");
