export const ROUTES = {
  home: "/",
  join: "/join/:token",
  signUp: "/sign-up",
  acceptInvite: "/invite/accept/:token",
  verify: "/verify",
  login: "/log-in",
  loginWithRedirect: "/log-in?redirectUrl",
  forgotPassword: "/log-in/forgot-password",
  resetPassword: "/reset-password",
  accountSettings: "/account/settings",
  orgs: "/orgs",
  org: "/orgs/:orgId",
  orgCrawls: "/orgs/:orgId/crawls(/crawl)(/:crawlId)",
  orgConfigs:
    "/orgs/:orgId/crawl-configs(/config)(/new)(/:crawlConfigId)(/edit)",
  orgBrowserProfiles:
    "/orgs/:orgId/browser-profiles(/profile)(/:browserProfileId)",
  orgSettings: "/orgs/:orgId/settings(/members)(/invite)",
  // org: "/orgs/:id/:tab",
  // orgNewResourceTab: "/orgs/:id/:tab/new",
  // orgAddMember: "/orgs/:id/:tab/add-member",
  // orgCrawl: "/orgs/:id/:tab/crawl/:crawlId",
  // browserProfile: "/orgs/:id/:tab/profile/:browserProfileId",
  browser: "/orgs/:orgId/browser-profiles/profile/browser/:browserId",
  // crawlTemplate: "/orgs/:id/:tab/config/:crawlConfigId",
  // crawlTemplateEdit: "/orgs/:id/:tab/config/:crawlConfigId?edit",
  // crawlTemplateNew: "/orgs/:id/:tab/new?jobType",
  users: "/users",
  usersInvite: "/users/invite",
  crawls: "/crawls",
  crawl: "/crawls/crawl/:crawlId",
} as const;

export const DASHBOARD_ROUTE = ROUTES.home;
