import type { Meta, StoryObj } from "@storybook/web-components";

import { renderComponent, type RenderProps } from "./ItemDependencyTree";

const meta = {
  title: "Features/Item Dependency Tree",
  component: "btrix-item-dependency-tree",
  tags: ["autodocs"],
  decorators: [],
  render: renderComponent,
  argTypes: {},
  args: {},
} satisfies Meta<RenderProps>;

export default meta;
type Story = StoryObj<RenderProps>;

export const Basic: Story = {
  args: {
    items: [
      {
        id: "item-storybook-id-1",
        type: "crawl",
        userid: "item-storybook-userid-1",
        userName: "Alice",
        oid: "item-storybook-oid-1",
        profileid: null,
        name: "",
        description: "",
        started: "2023-10-27T03:18:15Z",
        finished: "2023-10-27T03:18:37Z",
        state: "complete",
        stats: { found: "1", done: "1", size: "32491355" },
        fileSize: 16257194,
        fileCount: 1,
        tags: [],
        collectionIds: [],
        collections: [],
        crawlExecSeconds: 8,
        qaCrawlExecSeconds: 0,
        cid: "item-storybook-cid-1",
        firstSeed: "https://webrecorder.net/",
        seedCount: 1,
        profileName: null,
        stopping: false,
        shouldPause: false,
        manual: true,
        scale: 1,
        browserWindows: 4,
        crawlerChannel: "default",
        proxyId: null,
        image: null,
        qaRunCount: 0,
        activeQAStats: null,
        lastQAState: null,
        lastQAStarted: null,
        pageCount: 1,
        uniquePageCount: 1,
        filePageCount: 0,
        errorPageCount: 0,
        requiresCrawls: [
          "item-storybook-id-2",
          "item-storybook-id-3",
          "item-storybook-id-4",
        ],
        requiredByCrawls: [],
      },
      {
        id: "item-storybook-id-2",
        type: "crawl",
        userid: "item-storybook-userid-2",
        userName: "Alice",
        oid: "item-storybook-oid-2",
        profileid: null,
        name: "",
        description: "",
        started: "2023-10-27T03:18:15Z",
        finished: "2023-10-27T03:18:37Z",
        state: "complete",
        stats: { found: "1", done: "1", size: "32491355" },
        fileSize: 16257194,
        fileCount: 1,
        tags: [],
        collectionIds: [],
        collections: [],
        crawlExecSeconds: 8,
        qaCrawlExecSeconds: 0,
        cid: "item-storybook-cid-2",
        firstSeed: "https://example.com/",
        seedCount: 1,
        profileName: null,
        stopping: false,
        shouldPause: false,
        manual: true,
        scale: 1,
        browserWindows: 4,
        crawlerChannel: "default",
        proxyId: null,
        image: null,
        qaRunCount: 0,
        activeQAStats: null,
        lastQAState: null,
        lastQAStarted: null,
        pageCount: 1,
        uniquePageCount: 1,
        filePageCount: 0,
        errorPageCount: 0,
        requiresCrawls: [],
        requiredByCrawls: [],
      },
      {
        id: "item-storybook-id-3",
        type: "crawl",
        userid: "item-storybook-userid-3",
        userName: "Alice",
        oid: "item-storybook-oid-3",
        profileid: null,
        name: "",
        description: "",
        started: "2023-10-27T03:18:15Z",
        finished: "2023-10-27T03:18:37Z",
        state: "complete",
        stats: { found: "1", done: "1", size: "32491355" },
        fileSize: 16257194,
        fileCount: 1,
        tags: [],
        collectionIds: [],
        collections: [],
        crawlExecSeconds: 8,
        qaCrawlExecSeconds: 0,
        cid: "item-storybook-cid-3",
        firstSeed: "https://example.com/",
        seedCount: 1,
        profileName: null,
        stopping: false,
        shouldPause: false,
        manual: true,
        scale: 1,
        browserWindows: 4,
        crawlerChannel: "default",
        proxyId: null,
        image: null,
        qaRunCount: 0,
        activeQAStats: null,
        lastQAState: null,
        lastQAStarted: null,
        pageCount: 1,
        uniquePageCount: 1,
        filePageCount: 0,
        errorPageCount: 0,
        requiresCrawls: [],
        requiredByCrawls: [],
      },
    ],
  },
};
