// API v1.25.1
export default {
  total: 3,
  page: 1,
  pageSize: 20,
  items: [
    {
      id: "fake-79c9-4193-9b40-d64c4f8f76f4",
      name: "Social Media",
      slug: "social-media",
      oid: "x_example_org_id_x",
      description: null,
      caption: "",
      created: "2025-09-23T19:32:42Z",
      modified: "2025-10-05T00:03:10Z",
      lastStatsUpdateStarted: null,
      crawlCount: 9,
      pageCount: 3210,
      uniquePageCount: 2391,
      totalSize: 41290204995,
      dateEarliest: "2025-09-23T20:00:50.756000Z",
      dateLatest: "2025-10-05T00:03:01.997000Z",
      tags: [],
      access: "private",
      homeUrl: null,
      homeUrlTs: null,
      homeUrlPageId: null,
      resources: [],
      thumbnail: null,
      thumbnailSource: null,
      defaultThumbnailName: "thumbnail-cyan",
      allowPublicDownload: true,
      initialPages: [],
      preloadResources: [],
      pagesQueryUrl: "",
      downloadUrl: null,
      topPageHosts: [{ host: "example.com", count: 3 }],
      indexLastSavedAt: null,
      indexState: null,
      indexStats: null,
      runningUpdatesCount: 0,
    },
    {
      id: "fake-1bba-498d-af8b-a8b48c663e6a",
      name: "Portfolio (Client Work)",
      slug: "portfolio-client-work",
      oid: "x_example_org_id_x",
      description: null,
      caption: "",
      created: "2025-09-23T19:33:05Z",
      modified: "2025-10-05T00:03:10Z",
      lastStatsUpdateStarted: null,
      crawlCount: 1,
      pageCount: 1,
      uniquePageCount: 1,
      totalSize: 56713,
      dateEarliest: "2025-09-23T20:00:50.756000Z",
      dateLatest: "2025-10-05T00:03:01.997000Z",
      tags: [],
      access: "unlisted",
      homeUrl: null,
      homeUrlTs: null,
      homeUrlPageId: null,
      resources: [],
      thumbnail: null,
      thumbnailSource: null,
      defaultThumbnailName: "thumbnail-cyan",
      allowPublicDownload: true,
      initialPages: [],
      preloadResources: [],
      pagesQueryUrl: "",
      downloadUrl: null,
      topPageHosts: [{ host: "example.com", count: 3 }],
      indexLastSavedAt: null,
      indexState: null,
      indexStats: null,
      runningUpdatesCount: 0,
    },

    {
      id: "fake-2bba-498d-af8b-a8b48c663e6a",
      name: "Portfolio",
      slug: "portfolio",
      oid: "x_example_org_id_x",
      description: null,
      caption: "",
      created: "2025-09-23T19:34:52Z",
      modified: "2025-10-05T00:03:10Z",
      lastStatsUpdateStarted: null,
      crawlCount: 3,
      pageCount: 3,
      uniquePageCount: 1,
      totalSize: 170099,
      dateEarliest: "2025-10-05T00:03:01.997000Z",
      dateLatest: "2025-10-05T00:03:01.997000Z",
      tags: [],
      access: "public",
      homeUrl: null,
      homeUrlTs: null,
      homeUrlPageId: null,
      resources: [],
      thumbnail: null,
      thumbnailSource: null,
      defaultThumbnailName: "thumbnail-cyan",
      allowPublicDownload: true,
      initialPages: [],
      preloadResources: [],
      pagesQueryUrl: "",
      downloadUrl: null,
      topPageHosts: [{ host: "example.com", count: 3 }],
      indexLastSavedAt: null,
      indexState: null,
      indexStats: null,
      runningUpdatesCount: 0,
    },
  ],
};
