export default {
  total: 3,
  page: 1,
  pageSize: 10,
  items: [
    {
      name: "example.com site crawl",
      description: null,
      created: "2025-03-20T00:52:46Z",
      createdBy: "x_example_user_id_x",
      modified: "2026-05-04T18:02:37Z",
      modifiedBy: "x_example_user_id_x",
      autoAddCollections: [
        "fake-b08d-4738-b222-abbb6c575479",
        "fake-6944-4ce9-a716-c9cfdbc95f0c",
      ],
      inactive: false,
      rev: 15,
      crawlAttemptCount: 14,
      crawlCount: 14,
      crawlSuccessfulCount: 13,
      totalSize: 636867,
      lastCrawlId: "fake-sched-29803680",
      lastCrawlStartTime: "2026-09-01T00:00:00Z",
      lastStartedBy: "x_example_user_id_x",
      lastCrawlTime: "2026-09-01T00:03:47Z",
      lastCrawlState: "complete",
      lastCrawlSize: 57194,
      lastRun: "2026-09-01T00:03:47Z",
      isCrawlRunning: false,
      crawlFilenameTemplate: null,
      shareable: false,
      id: "fake-ff4f-4dc1-8de1-d5b30e2005f0",
      schedule: "0 0 1 * *",
      jobType: "custom",
      config: null,
      tags: [],
      crawlTimeout: 0,
      maxCrawlSize: 0,
      scale: 1,
      browserWindows: 4,
      oid: "x_example_org_id_x",
      profileid: null,
      crawlerChannel: "dev-2",
      proxyId: null,
      firstSeed: "https://example.com/",
      seedCount: 1,
      dedupeCollId: null,
      lastCrawlStopping: false,
      lastCrawlShouldPause: false,
      lastCrawlPausedAt: null,
      lastCrawlPausedExpiry: null,
      lastCrawlStats: { found: 1, done: 1, size: 81641, req_crawls: [] },
      profileName: null,
      createdByName: "User Name",
      modifiedByName: "User Name",
      lastStartedByName: "User Name",
    },
    {
      name: "",
      description: null,
      created: "2026-08-24T17:32:47Z",
      createdBy: "x_example_user_id_x",
      modified: "2026-08-24T17:32:47Z",
      modifiedBy: "x_example_user_id_x",
      autoAddCollections: [],
      inactive: false,
      rev: 0,
      crawlAttemptCount: 1,
      crawlCount: 1,
      crawlSuccessfulCount: 1,
      totalSize: 60619,
      lastCrawlId: "fake-sched-29802660",
      lastCrawlStartTime: "2026-08-31T07:00:00Z",
      lastStartedBy: "x_example_user_id_x",
      lastCrawlTime: "2026-08-31T07:03:15Z",
      lastCrawlState: "complete",
      lastCrawlSize: 60619,
      lastRun: "2026-08-31T07:03:15Z",
      isCrawlRunning: false,
      crawlFilenameTemplate: null,
      shareable: false,
      id: "fake-7879-497b-8b70-64a655323f04",
      schedule: "0 7 * * 1",
      jobType: "custom",
      config: null,
      tags: [],
      crawlTimeout: 3600,
      maxCrawlSize: 10000000000,
      scale: null,
      browserWindows: 4,
      oid: "x_example_org_id_x",
      profileid: null,
      crawlerChannel: "default",
      proxyId: null,
      firstSeed: "https://example.com/",
      seedCount: 1,
      dedupeCollId: null,
      lastCrawlStopping: false,
      lastCrawlShouldPause: false,
      lastCrawlPausedAt: null,
      lastCrawlPausedExpiry: null,
      lastCrawlStats: { found: 1, done: 1, size: 85070, req_crawls: [] },
      profileName: null,
      createdByName: "User Name",
      modifiedByName: "User Name",
      lastStartedByName: "User Name",
    },
    {
      name: "example.com (with page limit)",
      description: null,
      created: "2025-07-09T18:24:22Z",
      createdBy: "x_example_user_id_x",
      modified: "2026-07-27T18:47:59Z",
      modifiedBy: "x_example_user_id_x",
      autoAddCollections: ["fake-d742-4726-876e-8e086d05541c"],
      inactive: false,
      rev: 172,
      crawlAttemptCount: 55,
      crawlCount: 55,
      crawlSuccessfulCount: 30,
      totalSize: 135732383578,
      lastCrawlId: "fake-manual-20260812013001",
      lastCrawlStartTime: "2026-08-12T01:30:01Z",
      lastStartedBy: "x_example_user_id_x",
      lastCrawlTime: "2026-08-12T01:38:22Z",
      lastCrawlState: "canceled",
      lastCrawlSize: 0,
      lastRun: "2026-08-12T01:38:22Z",
      isCrawlRunning: false,
      crawlFilenameTemplate: null,
      shareable: false,
      id: "fake-7b5b-4407-ad39-9f4aa89adee4",
      schedule: "",
      jobType: "custom",
      config: null,
      tags: [],
      crawlTimeout: 3600,
      maxCrawlSize: 0,
      scale: null,
      browserWindows: 2,
      oid: "x_example_org_id_x",
      profileid: "fake-eea9-475c-9951-ec8b7a60d9b0",
      crawlerChannel: "default",
      proxyId: null,
      firstSeed: "https://example.com/",
      seedCount: 1,
      dedupeCollId: null,
      lastCrawlStopping: false,
      lastCrawlShouldPause: false,
      lastCrawlPausedAt: null,
      lastCrawlPausedExpiry: null,
      lastCrawlStats: {
        found: 1000,
        done: 15,
        size: 1299946001,
        req_crawls: [],
      },
      profileName: null,
      createdByName: "User Name",
      modifiedByName: "User Name",
      lastStartedByName: "User Name",
    },
  ],
};
