// API v1.25.1
export default {
  total: 3,
  page: 1,
  pageSize: 20,
  items: [
    {
      id: "fake-sched-29803680",
      type: "crawl",
      userid: "x_example_user_id_x",
      userName: "User Name",
      oid: "x_example_org_id_x",
      profileid: null,
      name: "example.com site crawl",
      description: "",
      started: "2026-09-01T00:00:00Z",
      finished: "2026-09-01T00:03:47Z",
      state: "complete",
      stats: { found: 1, done: 1, size: 81641, req_crawls: [] },
      fileSize: 57194,
      fileCount: 1,
      pendingSize: 24447,
      fileSizeWithDeps: null,
      tags: [],
      dedupeCollId: null,
      collectionIds: [
        "fake-b08d-4738-b222-abbb6c575479",
        "fake-6944-4ce9-a716-c9cfdbc95f0c",
      ],
      crawlExecSeconds: 8,
      qaCrawlExecSeconds: 0,
      config: null,
      cid: "fake-ff4f-4dc1-8de1-d5b30e2005f0",
      firstSeed: "https://example.com/",
      seedCount: 1,
      profileName: null,
      stopping: false,
      shouldPause: false,
      pausedAt: null,
      rateLimitedAt: null,
      manual: false,
      cid_rev: 15,
      scale: 1,
      browserWindows: 4,
      storageQuotaReached: false,
      execMinutesQuotaReached: false,
      crawlerChannel: "dev-2",
      proxyId: null,
      image:
        "registry.digitalocean.com/btrix/webrecorder/browsertrix-crawler:dev-2",
      reviewStatus: null,
      qaRunCount: 0,
      activeQAStats: null,
      lastQAState: null,
      lastQAStarted: null,
      pageCount: 1,
      uniquePageCount: 1,
      filePageCount: 0,
      errorPageCount: 0,
      version: 2,
      errors: [],
      behaviorLogs: [],
      requiresCrawls: [],
      requiredByCrawls: [],
      missingRequiresCrawls: null,
      dedupeStats: null,
    },
    {
      id: "fake-sched-29802660",
      type: "crawl",
      userid: "x_example_user_id_x",
      userName: "User Name",
      oid: "x_example_org_id_x",
      profileid: null,
      name: "",
      description: "",
      started: "2026-08-31T07:00:00Z",
      finished: "2026-08-31T07:03:15Z",
      state: "complete",
      stats: { found: 1, done: 1, size: 85070, req_crawls: [] },
      fileSize: 60619,
      fileCount: 1,
      pendingSize: 24451,
      fileSizeWithDeps: null,
      tags: [],
      dedupeCollId: null,
      collectionIds: [],
      crawlExecSeconds: 11,
      qaCrawlExecSeconds: 0,
      config: null,
      cid: "fake-7879-497b-8b70-64a655323f04",
      firstSeed: "https://example.com/",
      seedCount: 1,
      profileName: null,
      stopping: false,
      shouldPause: false,
      pausedAt: null,
      rateLimitedAt: null,
      manual: false,
      cid_rev: 0,
      scale: 1,
      browserWindows: 4,
      storageQuotaReached: false,
      execMinutesQuotaReached: false,
      crawlerChannel: "default",
      proxyId: null,
      image: "docker.io/webrecorder/browsertrix-crawler:edge",
      reviewStatus: null,
      qaRunCount: 0,
      activeQAStats: null,
      lastQAState: null,
      lastQAStarted: null,
      pageCount: 1,
      uniquePageCount: 1,
      filePageCount: 0,
      errorPageCount: 0,
      version: 2,
      errors: [],
      behaviorLogs: [],
      requiresCrawls: [],
      requiredByCrawls: [],
      missingRequiresCrawls: null,
      dedupeStats: null,
    },
    {
      id: "fake-manual-20260810231145",
      type: "crawl",
      userid: "x_example_user_id_x",
      userName: "admin",
      oid: "x_example_org_id_x",
      profileid: "e36109fd-eea9-475c-9951-ec8b7a60d9b0",
      name: "example.com (with page limit)",
      description: "",
      started: "2026-08-10T23:11:45Z",
      finished: "2026-08-10T23:12:42Z",
      state: "canceled",
      stats: { found: 241, done: 1, size: 3253047, req_crawls: [] },
      fileSize: 0,
      fileCount: 0,
      pendingSize: 3253047,
      fileSizeWithDeps: null,
      tags: [],
      dedupeCollId: null,
      collectionIds: [],
      crawlExecSeconds: 32,
      qaCrawlExecSeconds: 0,
      config: null,
      cid: "fake-7b5b-4407-ad39-9f4aa89adee4",
      firstSeed: "https://example.com/",
      seedCount: 1,
      profileName: "My Profile",
      stopping: false,
      shouldPause: false,
      pausedAt: null,
      rateLimitedAt: null,
      manual: true,
      cid_rev: 172,
      scale: 1,
      browserWindows: 2,
      storageQuotaReached: false,
      execMinutesQuotaReached: false,
      crawlerChannel: "default",
      proxyId: "",
      image: "docker.io/webrecorder/browsertrix-crawler:1.14.0",
      reviewStatus: null,
      qaRunCount: 0,
      activeQAStats: null,
      lastQAState: null,
      lastQAStarted: null,
      pageCount: 0,
      uniquePageCount: 0,
      filePageCount: 0,
      errorPageCount: 0,
      version: 2,
      errors: [],
      behaviorLogs: [],
      requiresCrawls: [],
      requiredByCrawls: [],
      missingRequiresCrawls: null,
      dedupeStats: null,
    },
  ],
};
