apiVersion: btrix.cloud/v1
kind: CrawlJob
metadata:
  name: crawljob-{{ id }}
  labels:
    crawl: "{{ id }}"
    role: "job"
    oid: "{{ oid }}"
    userid: "{{ userid }}"

spec:
  selector:
    matchLabels:
      crawl: "{{ id }}"

  id: "{{ id }}"
  userid: "{{ userid }}"
  cid: "{{ cid }}"
  oid: "{{ oid }}"
  scale: {{ scale }}
  maxCrawlSize: {{ max_crawl_size }}
  ttlSecondsAfterFinished: 30

  {% if expire_time %}
  expireTime: "{{ expire_time }}"
  {% endif %}
