apiVersion: btrix.cloud/v1
kind: CrawlJob
metadata:
  name: crawljob-{{ id }}
  labels:
    crawl: "{{ id }}"
    role: "job"
    btrix.org: "{{ oid }}"
    btrix.user: "{{ userid }}"
    btrix.storage: "{{ storage_name }}"

spec:
  selector:
    matchLabels:
      crawl: "{{ id }}"

  id: "{{ id }}"
  userid: "{{ userid }}"
  cid: "{{ cid }}"
  oid: "{{ oid }}"
  scale: {{ scale }}
  maxCrawlSize: {{ max_crawl_size }}
  manual: {{ manual }}
  ttlSecondsAfterFinished: 30

  storageName: "{{ storage_name }}"

  {% if expire_time %}
  expireTime: "{{ expire_time }}"
  {% endif %}
