---
k3s_version: v1.22.3+k3s1
ansible_user: debian
systemd_dir: /etc/systemd/system
controller_ip: "{{ hostvars[groups['controller'][0]]['ansible_host'] | default(groups['controller'][0]) }}"
extra_server_args: "--disable traefik"
extra_agent_args: ""
project_name: browsertrix-cloud
domain: my-domain.example.com
email: test@example.com
