name: Scheduled Crawl Test (Dev)

on:
  schedule:
    # Run daily at 14:00 UTC
    - cron: "0 14 * * *"

  workflow_dispatch:

env:
  BROWSERTRIX_HOST: "https://dev.browsertrix.com"
  BROWSERTRIX_USER: ${{ secrets.DEV_DAILY_TEST_USER }}
  BROWSERTRIX_PASSWORD: ${{ secrets.DEV_DAILY_TEST_PASSWORD }}
  DAILY_TEST_ORG: "85449160-6632-419a-a9fc-bac35a3d6d73"
  DAILY_TEST_CRAWLCONFIG: "a1d07112-85f2-4182-aa69-fdf597c4c0cc"

jobs:
  daily-scheduled-crawl-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Install dependencies
        run: |
          cd backend/
          uv sync --group test --python 3.14
          # We need this extra package to validate it
          uv pip install wacz[signing]

      - name: Run tests
        run: |
          set -euo pipefail

          cd backend
          crawl="$(uv run ../scripts/btrix-cli.py crawls list-from-crawlconfig --org-id $DAILY_TEST_ORG --crawl-config-id a1d07112-85f2-4182-aa69-fdf597c4c0cc | head -2 | tail -1)"
          crawl_id=$(echo "$crawl" | awk -F'\t' '{ print $1 }')
          finished=$(echo "$crawl" | awk -F'\t' '{ print $4 }')

          if [ $(($EPOCHSECONDS - $(gdate -d 2026-10-06T14:03:29Z +%s))) -ge 86400 ]; then
            echo "Scheduled crawl didn't run within the past 24 hours!"
            exit 1
          fi

          uv run ../scripts/btrix-cli.py crawls download --org-id $DAILY_TEST_ORG --crawl-id $crawl_id --download-path /tmp/daily-test.wacz

          uv run wacz validate --verify-auth -f /tmp/daily-test.wacz
