name: Publish Docs
on:
  workflow_dispatch:
    inputs:
      docs_source_url:
        description: 'URL of Browsertrix Deployment to copy API docs from'
        required: false
        default: 'https://app.browsertrix.com'

  release:
    types: [published]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy_docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v6
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - run: pip install zensical requests pyyaml

      - name: Generate Helm Chart Index
        run: python ./scripts/generate-helm-index.py > ./frontend/docs/docs/helm-repo/index.yaml

      - name: Copy Docs Files
        run: frontend/docs/copy-api-docs.sh
        env:
          DOCS_SOURCE_URL: ${{ github.event.inputs.docs_source_url || 'https://app.browsertrix.com' }}
          ENABLE_ANALYTICS: true

      - name: Build Docs
        run: cd frontend/docs; zensical build --clean
        env:
          ENABLE_ANALYTICS: true

      - uses: actions/upload-pages-artifact@v5
        with:
          path: frontend/docs/site

      - uses: actions/deploy-pages@v5
        id: deployment

