name: Backend Lint Check

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd backend/
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -U black pylint

      - name: Style Check
        run: |
          black --check backend/btrixcloud/

      - name: Lint Check
        run: |
          cd backend/
          pylint btrixcloud/
