name: Browsertrix Cloud Release Build

on:
  release:
    types: [published]
  push:
 
jobs:
  btrix-release:
    runs-on: ubuntu-22.04

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Free Disk space
        shell: bash
        run: |
          sudo rm -rf /usr/local/lib/android  # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET

      -
        name: Set Env Vars
        run: |
          echo VERSION=`cat version.txt` >> $GITHUB_ENV
          echo GIT_COMMIT_HASH=`git rev-parse --short HEAD` >> $GITHUB_ENV
          echo GIT_BRANCH_NAME=`git rev-parse --abbrev-ref HEAD` >> $GITHUB_ENV

      -
        name: Build Backend
        uses: docker/build-push-action@v3
        with:
          context: backend
          platforms: linux/amd64,linux/arm64
          #push: true
          tags: ${{ env.REPO_PREFIX }}webrecorder/browsertrix-backend:${{ env.VERSION }}, webrecorder/browsertrix-backend:latest
          cache-from: type=gha,scope=backend
          cache-to: type=gha,scope=backend,mode=max

      -
        name: Build Frontend Yarn Build
        uses: docker/build-push-action@v3
        env:
          HUSKY: 0
        with:
          context: frontend
          platforms: linux/amd64
          load: true
          file: frontend/builder.Dockerfile
          build-args: |
            VERSION=${{ env.VERSION }}
            GIT_COMMIT_HASH=${{ env.GIT_COMMIT_HASH }}
            GIT_BRANCH_NAME=${{ env.GIT_BRANCH_NAME }}

          tags: user/browsertrix-frontend-builder:test
          cache-from: type=gha,scope=frontend-builder
          cache-to: type=gha,scope=frontend-builder,mode=max

      -
        name: Copy Frontend dist
        run: |
          docker cp $(docker create --name bc-frontend-builder-temp user/browsertrix-frontend-builder:test):/app/dist ./frontend/.dist && docker rm bc-frontend-builder-temp

      -
        name: Build Frontend
        uses: docker/build-push-action@v3
        with:
          context: frontend
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
            GIT_COMMIT_HASH=${{ env.GIT_COMMIT_HASH }}
            GIT_BRANCH_NAME=${{ env.GIT_BRANCH_NAME }}

          tags: ${{ env.REPO_PREFIX }}webrecorder/browsertrix-frontend:${{ env.VERSION }}, webrecorder/browsertrix-frontend:latest
          cache-from: type=gha,scope=frontend
          cache-to: type=gha,scope=frontend,mode=max

